### ISSUE TITLE
transmission-openvpn[Docker] - can't connect to host machine: "Temporary failure in name resolution (tr-dht.c:128)"

### ISSUE THREAD

**Issue by indy1172** [johnnyq/simpnas#1]
Regarding docker container for transmission-openvpn --- the docker container containing transmission and OpenVPN by default inherits the nameserver info from the host, which in my case is
domain hsd1.pa.comcast.net
search hsd1.pa.comcast.net
nameserver 75.75.75.75
nameserver 75.75.76.76
_/etc/resolv.conf_

PIA VPN doesnt like these settings --

Solution: add to container's run script: --ns 8.8.8.8 --ns 8.8.4.4
They are Google's nameservers and are not blocked by the VPN apparently.

/mnt/<VOLUME>/transmission-ovpn/transmission.log
unable [2020-04-20 02:15:20.743] DHT dht.transmissionbt.com:6881: Temporary failure in name resolution (tr-dht.c:128)

I wish I had more insight on why PIA doesn't automatically try resolving other nameservers.  It's been a long night debugging this, and it's still relatively confusing.

**Comment by johnnyq** [comment]
Thank you for reporting and finding a solution The reason why its not resolving is when you connect over the VPN your out of the Comcast network, therefore resolving address will not work. I have updated the code with your idea. You can manually add a dns server upon the creation of the app now. Thank again for your dedication to this project.
Commit 
48a5152b668b144035215836e48a45c7dc8eeec7

**Comment by johnnyq** [comment]
please report back to make sure this works, so we can close this issue out. but please update first by going to update click update simpnas, delete the transmission-ovpn app and then re-install it with the 8.8.8.8 DNS server. Thanks

**Comment by indy1172** [comment]
Update did not take. Tried rebooting. 
![image](https://user-images.githubusercontent.com/36959022/79804169-7b179280-8331-11ea-8496-9217b24b84b7.png)

**Comment by johnnyq** [comment]
fixed, if you make a change to anything in simpnas the update which use git pull will break and want to merge your code. I created a force update button to reset the repo back to current and overwrite any local changes you made to /simpnas folder this may end up being the future way of doing updates to prevent update breakage
