### ISSUE TITLE
v0.01 (2020-04-21) Transmission + OpenVPN not part of new app list

### ISSUE THREAD

**Issue by indy1172** [johnnyq/simpnas#2]
Though when I did the update and rebooted, Transmission+OpenVPN remained installed and launched right up with the address + :9091, the feature is not listed in the new app list UI (see photo)

![image](https://user-images.githubusercontent.com/36959022/80272218-63c00880-8695-11ea-91c3-1383680df53a.png)

**Comment by johnnyq** [comment]
The way it checks to see if its installed is it checks the docker config folder and checks to see if transmission-ovpn exists. We no longer have sepeate names for transmission we combined it into 1 named transmission. We recommend removing your old vm by doing a docker stop transmission-ovpn docker rm transmission-ovpn and then reeinstalling the new version from the interface.
