### ISSUE TITLE
During setup

### ISSUE THREAD

**Issue by tido-** [johnnyq/simpnas#27]
**Volume Creation**
Volume Name - should be the last line, because if I click RESCAN it will blank the diskname I just entered for the disk. 
So, I think you should first:
 choose the drive and File System Type and then give a name to it.

**Password**
I would appreciate an information like:  Enable Cookies to login after the reboot with: administrator 

**UTF-8**
In the file: post.php, is a line: $stringData = "UUID=$uuid    /volumes/$name      $filesystem    defaults 0 0\n";
I would add UTF8 because french, germans and we like to use letters like èéàüäö. An extract of my /etc/fstab:
ext4    defaults,utf8    0    0

**Comment by johnnyq** [comment]
That makes sense in volume creation, we will rework the order. I'm not sure about the login as we do not use cookies.
We will enable UTF-8, thanks for the tip I learn something new everyday =]

**Comment by tido-** [comment]
> I'm not sure about the login as we do not use cookies.

I have a blocker : https://github.com/gorhill/uMatrix, with which I see & control basically everything and it blocks cookie in standard function. IIRC, I couldn't login before I allowed Cookies. Are you using cookie-blocker too?
May be it is part of the JS or PHP framework you are using?

**Comment by johnnyq** [comment]
@tido we do not use any frameworks, except a css framework which is bootstrap, but there shouldn't be anything that prevents you to login. its all php session based so the whole login process is server side. lets take a few steps back. when you input your username password then hit login does it let you in or come back with an error on the screen?

**Comment by tido-** [comment]
You see were my mouse is, it says 10 cookies for this Website. It is right now red, because I block it. And yes, without cookie just come back on the screen - no error, no login too.
The 10, because NC and bitwarden leave their's too.

![Bildschirmfoto zu 2020-07-08 15-51-17](https://user-images.githubusercontent.com/10658438/86927109-31219a00-c133-11ea-882f-548c69b80bdf.png)

**Comment by johnnyq** [comment]
Excellent Find. that is strange okay ill look into why and  where these cookies are coming from

**Comment by tido-** [comment]
> its all php session based

If it is as you say, wouldn't I see a number in the login link: http://192.168.11.9:81/login.php  or how do you identify the session?
You don't need to explain me, I am not a programmer, just my thoughts.

**Comment by johnnyq** [comment]
@tido- We moved the volume name below add disk
We also removed filesystem and now default back to ext4, BTRFS was causing too many problems and may enabled it back later on
We do not need to add utf-8 to the fstab as ext4 already supports this by default.
I'll need some help with the cookies, so i'm going to close this issue out and open another one regarding cookies
