### ISSUE TITLE
Information in the WebUI

### ISSUE THREAD

**Issue by tido-** [johnnyq/simpnas#28]
**Section of the APPS** title, like:
In here all apps are 64-Bit, all Apps are applied in Docker-Containers 

**Dashboard**
The graphics in the section Stats & Services behave different when you play with the windows width.
Groups & Docker will shrink first. Then Shares & Samba

**Comment by johnnyq** [comment]
I see that in Dashboard ill work on a fix, also add a CPU compatibility section to Apps. All apps will use docker it makes it simple and contained.

**Comment by johnnyq** [comment]
473e8750af03e861a707b25360ccb3fad4dbba08
Fixed Distorted Dashboard at various view points
We are working on a new apps layout with better seperation of installed apps and apps that can be installed. with some more details. coming soon
