### ISSUE TITLE
Feature Requests: Add Alert logs / Email Notifications

### ISSUE THREAD

**Issue by johnnyq** [johnnyq/simpnas#4]
Alerts to email and log

Daily
Volume Usage > 80% - Volume-Name - Low Disk Space
Check SMART Health if failing - HDD VendorName is failing

Hourly
30min load average  > 5 - High Load
swap > 80% - High Swap Usage
Memory > 80% - High Memory Usage
Service Checks

- Docker
- SSH
- Samba
- SimpNAS Web UI

**Comment by tido-** [comment]
Is this still open?

**Comment by johnnyq** [comment]
Hi @tido- Yes it still open, we implemented most of the functionality of notifications, we are working on how we are going to implement it in cron

**Comment by johnnyq** [comment]
Done
