### ISSUE TITLE
SSH directly into docker (minecraft-server)

### ISSUE THREAD

**Issue by indy1172** [johnnyq/simpnas#47]
Hi there. I installed the following docker onto my instance of Simpnas:
[docker-minecraft-server](https://github.com/itzg/docker-minecraft-server)
All works well, and I am able to connect to the host IP via Minecraft client, and control the server using the cli tool within the container. I would like to be able to SSH directly into the container. I'm having trouble getting started with that. Any insight?

**Comment by johnnyq** [comment]
Hi @indy1172 your best bet is to initiate a shell into your docker container. use the following command on your docker host
`docker exec -it CONTAINER-NAME bash`

Replace CONTAINER-NAME with the name of the container

use `docker ps `to get all your running docker containers and their names

Containers only contain the necessary libraries and binaries the specific app needs to run therefore they usually don't contain openssh-server.

Hope this helps and good luck

**Comment by johnnyq** [comment]
Closing
