### ISSUE TITLE
a few questions 

### ISSUE THREAD

**Issue by Greylinux** [johnnyq/simpnas#51]
Hi , 

I've only just discovered this project via the armbian forum .
I am seriously impressed!

I did ask a few questions on armbian forum but I'm wondering if it's best to ask on the simpnas forum ?

One question I didnt ask on there but I will here is do you have an option for donations . I believe for a project like this having the option to receive a bit of pay for your efforts is a must . I can't give a huge donation but I would like to support the project if I can .

 I would also like to encourage the use of your simpnas solution by mentioning it on Mastodo,  hopefully this will promote your project a little .

Finally do you predict that there will be a stable release this year ? Not that this will stop me switching from openmediavault to your beta  but just asking an open query .

**Comment by johnnyq** [comment]
Hi @GreyMarvel Thank you for the kind compliments. I'm glad you can make some use of SimpNAS. Its still very early in development indeed. I just read your post on Armbian and you mentioned installing additional docker containers and such. It is not the intent of the project but it shouldn't be a be a problem.

I would love to accept donations that could keep us motivated, maybe ill set up a paypal and put a link on the site for donations. Thank you for the suggestion and helping the project out.

Please do mention us on Mastdo we would very much appreciate it. The more fans and more bug reporters the better.

Stable Release come as an early Christmas Present ;-)

**Comment by Greylinux** [comment]
An early Christmas present ! This is excellent news . I mentioned your project on mastodon and I mentioned it on the pine64 forum as well . I thinking of running simpnas on my rockpro64 NAS,  as another user has done on the Armbian forum.  Here's the link https://forum.pine64.org/showthread.php?tid=11948  to the pine64 forum thread it's had quite a few views so far .
As long as it shouldn't conflict with the simpnas setup I'll be running other containers alongside as I mentioned and I can comment back here or on the Armbian forum of my experience if it helps you . But for now I'll close this issue and let you get back to the real issues.

Thanks again for your hard work .

**Comment by Greylinux** [comment]
Ok, so I set up SimpNAS and seriously it's amazing , the very sleek and simple interface is great . I will be doing a tutorial write-up on the pine64 form and the SimpNAS forum if that's alright with you.
I did discover some issues along the way with my setup but all were resolved and currently I'm running SimpNAS with several docker containers running using docker-compose .

I do have some recommendations but where would be best to post them ? on here as a new issue or on the SimpNAS forum ?

Thanks again for your assistance John .

**Comment by johnnyq** [comment]
Hi @GreyMarvel Im so glad you like it, its nice to have a fan base as this project was initially just for fun. I really appreciate you spreading the word. I would recommend opening each issue under github, but please one post per issue. This allow for better tracking, it can be feature requests or bug reports.
