### ISSUE TITLE
iptables firewall option  in network tab 

### ISSUE THREAD

**Issue by Greylinux** [johnnyq/simpnas#53]
Hi Johnny,

adding a firewall option in the network tab  that users can choose to enable would be a great option . however as I discovered adding iptable rules can affect the rules that docker adds. on option was to add a config file for the iptable rules and then creating a service to run the file at boot so that it doesnt affect the docker rules that exist.

here are the links that helped me understand [here](https://medium.com/swlh/manage-iptables-firewall-for-docker-kubernetes-daa5870aca4d) 
and [here](https://unrouted.io/2017/08/15/docker-firewall/)

my config file looks like this 

```
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:FILTERS - [0:0]
:DOCKER-USER - [0:0]

-F INPUT
-F DOCKER-USER
-F FILTERS

# BASIC Allow
-A INPUT -i lo -j ACCEPT

# Chain to FILTERS
-A INPUT -j FILTERS
-A DOCKER-USER -i eth0 -j FILTERS

# COMMON FIREWALL RULES

# ALLOW something
-A FILTERS -p all -j ACCEPT -m conntrack --ctstate ESTABLISHED,RELATED
-A FILTERS -p icmp --source 192.168.1.0/24 -j ACCEPT
-A FILTERS -p tcp --source 192.168.1.0/24 --dport 22 -j ACCEPT
-A FILTERS -p tcp --source 192.168.1.0/24 --dport 81 -j ACCEPT
-A FILTERS -p tcp --source 192.168.1.0/24 --dport 82 -j ACCEPT
-A FILTERS -p tcp --source 192.168.1.0/24 --dport 139 -j ACCEPT
-A FILTERS -p tcp --source 192.168.1.0/24 --dport 445 -j ACCEPT
-A FILTERS -p tcp --dport 80 -j ACCEPT
-A FILTERS -p tcp --dport 443 -j ACCEPT
-A FILTERS -p tcp --source 192.168.1.0/24 --dport 8123 -j ACCEPT
-A FILTERS -p tcp --source 192.168.1.0/24 --dport 8096 -j ACCEPT
-A FILTERS -p udp --source 192.168.1.0/24 --dport 1900 -j ACCEPT
-A FILTERS -p udp --source 192.168.1.0/24 --dport 7359 -j ACCEPT
-A FILTERS -p tcp --source 192.168.1.0/24 --dport 8000 -j ACCEPT
-A FILTERS -p tcp --source 192.168.1.0/24 --dport 9000 -j ACCEPT
# DENY something


###################################################################
### special cases for servers
### please modify by the server



### end special cases
############################################################

# FINAL REJECT
# Optional logging
#-A FILTERS -m limit --limit 5/min -j LOG --log-prefix "iptables_INPUT_denied: " --log-level 7
-A FILTERS -p all -j REJECT

COMMIT
```

as the links suggest add the config to the kernel using 

`iptables-restore -n /etc/iptables.conf`

and then create a service to run at boot .

additional rules created in the web interface could add rules to the filters section of the config file.

**Comment by johnnyq** [comment]
Hi @GreyMarvel We don't plan on implementing any firewall with SimpNAS as SimpNAS is meant to be placed behind a hardware firewall and placed on a trusted network. Firewalls really should be implemented at the border of your network and the internet using a firewall appliances like pfSense.

**Comment by johnnyq** [comment]
closing for now

**Comment by Greylinux** [comment]
> closing for now

I completely understand, why this shouldn't be added . I always go a bit overkill , I currently have SimpNAS running behind the openwrt  routers firewall . I always have a firewall on each of my devices so I can control how they communicate on the local network . 
But this is certainly not what most people would need or consider .

Thanks again @johnnyq
